In [149]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
from currency_converter import CurrencyConverter # currency_converter from EUR to USD
from sqlalchemy import create_engine
from csv import writer

In [150]:
#!conda install -c anaconda sqlalchemy

In [151]:
# Convert from EUR to USD
# pip install --user currencyconverter

In [152]:
# pip install cloudmersive-currency-api-client

In [153]:
df2 = pd.read_csv('laptop_price.csv', encoding='latin-1')
df4 = pd.read_csv('LaptopPricePrediction.csv', encoding='latin-1') #df = df.set_index('laptop_ID')
display(df2.head(2), df4.head(2))

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94

,Unnamed: 0,Name,Processor,RAM,Operating System,Storage,Display,Warranty,Price,rating
0,0,Lenovo Ideapad S145 Core i5 10th Gen - (8 GB/1...,Intel Core i5 Processor (10th Gen),8 GB DDR4 RAM,64 bit Windows 10 Operating System,1 TB HDD,39.62 cm (15.6 inch) Display,1 Year Onsite Warranty,"â¹43,990",3.9
1,1,Lenovo IdeaPad Core i3 11th Gen - (8 GB/256 GB...,Intel Core i3 Processor (11th Gen),8 GB DDR4 RAM,64 bit Windows 10 Operating System,256 GB SSD,35.56 cm (14 Inch) Display,1 Year Onsite Warranty,"â¹43,990",4.2

In [154]:
display(df2.shape, df4.shape)

(1303, 13)

(550, 10)

In [155]:
display(df2.columns, df4.columns)

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

Index(['Unnamed: 0', 'Name', 'Processor', 'RAM', 'Operating System', 'Storage',
       'Display', 'Warranty', 'Price', 'rating'],
      dtype='object')

In [156]:
print(df2.info(),"\n")
print(df4.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        550 non-null    int64
 1   Name              550 non-null    object
 2   Processor         550 non-null    object
 3   RAM               550 non-null    object
 4   Operating System  550 non-null    object
 5   Storage           550 non-null    object
 6   Display           550 non-null    object
 7   Warranty          550 non-null    object
 8   Price             550 non-null    object
 9   rating            550 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 43.1+ KB
None

In [157]:
data_duplicated2=df2[df2.duplicated()]
data_duplicated2

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros]
Index: []

In [158]:
data_duplicated4=df4[df4.duplicated()]
data_duplicated4

Empty DataFrame
Columns: [Unnamed: 0, Name, Processor, RAM, Operating System, Storage, Display, Warranty, Price, rating]
Index: []

### df2  dataset

In [159]:
# Convert OpSys column
# df2['OpSys'].unique()
os_dict1 = {
    "Windows 7": "win7",
    "Windows 10": "win10",#
    "macOS": "mac", #
    "No OS": "No OS", #
    "Mac OS X" :"Mac OS X", #
    "Linux": "Linux",#
    "Android" : "Android",#
    "Windows 10 S": "win10_sec",#
    "Chrome OS": "chrome"#
}
df2["OpSys"]= df2["OpSys"].apply(lambda x: os_dict1.get(x, np.nan))
#=================================================================
# Convert RAM colunm to number
# df2['Ram'].unique() 
#df2.Ram = pd.to_numeric(df2.Ram.str.replace('GB', ''),errors="coerce")
df2['Ram'] = df2['Ram'].apply(lambda x: x.split("GB")[0]).astype("int64")
#=================================================================
# Convert from EUR to USD
df2["Price-USD"] = df2["Price_euros"]*1.13

In [160]:
#df2.tail()
df2.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price-USD
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,mac,1.37kg,1339.69,1513.8497
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,mac,1.34kg,898.94,1015.8022
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,649.7500
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,mac,1.83kg,2537.45,2867.3185
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,mac,1.37kg,1803.60,2038.0680

In [161]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   int64
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
 13  Price-USD         1303 non-null   float64
dtypes: float64(3), int64(2), object(9)
memory usage: 142.6+ KB

##### =========================================== df4 dataset ==================================================

### Preprocessing the data
### Cleaning the data

In [162]:
df4.head(2)

,Unnamed: 0,Name,Processor,RAM,Operating System,Storage,Display,Warranty,Price,rating
0,0,Lenovo Ideapad S145 Core i5 10th Gen - (8 GB/1...,Intel Core i5 Processor (10th Gen),8 GB DDR4 RAM,64 bit Windows 10 Operating System,1 TB HDD,39.62 cm (15.6 inch) Display,1 Year Onsite Warranty,"â¹43,990",3.9
1,1,Lenovo IdeaPad Core i3 11th Gen - (8 GB/256 GB...,Intel Core i3 Processor (11th Gen),8 GB DDR4 RAM,64 bit Windows 10 Operating System,256 GB SSD,35.56 cm (14 Inch) Display,1 Year Onsite Warranty,"â¹43,990",4.2

In [ ]:
# Create two columns from Name column
df4["Company"]= df4['Name'].str.split(' ').str[0] #.replace('-' , ' ' )
df4['Product'] = df4.Name.str.split(' ').str[1:3].str.join(' ')

In [163]:
df4['RAM'].unique()

array(['8 GB DDR4 RAM', '4 GB DDR4 RAM', '16 GB DDR4 RAM',
       '8 GB LPDDR4X RAM', '8 GB LPDDR3 RAM', '32 GB LPDDR4X RAM',
       '16 GB LPDDR4X RAM', '16 GB LPDDR3 RAM', '8 GB DDR3 RAM',
       '16 GB DDR3 RAM', '32 GB DDR4 RAM',
       'Upgradable SSD Upto 512 GB and RAM Upto 32 GB', '4 GB DDR3 RAM',
       '12 GB DDR4 RAM'], dtype=object)

In [164]:
# Delete the word RAM from the RAM column
# df4.RAM = df4.RAM.str.split(' ').str[0:3].str.join(' ')
# Convert RAM colunm to number
df4.RAM = pd.to_numeric(df4.RAM.str.split(' ').str[0],errors="coerce")
## df4["RAM"] = df4["RAM"].apply(lambda x: x.split("GB")[0]).astype("int64")
## df4.RAM = df4.RAM.str.split(' ').str[0]#.astype("int64")
## df4.RAM = df4.RAM.astype("int64")
#==================================================
# Convert Operating System column
# df4['Operating System'].unique()
os_dict = {
    "64 bit Windows 10 Operating System": "64-bit win10",
    "Windows 10 Operating System": "win10",
    "Mac OS Operating System": "mac",
    "Pre-installed Genuine Windows 10 Operating System (Includes Built-in Security, Free Automated Updates, Latest Features)":
        "win10_sec",
    "DOS Operating System":"dos",
    "64 bit Chrome Operating System": "64-bit chrome"
}
df4["Operating System"]= df4["Operating System"].apply(lambda x: os_dict.get(x, np.nan))
#=======================================================
# Convert Display size to number
df4.Display = pd.to_numeric(
    df4.Display.str.split(' ').str[0].replace(r'[^0-9.]','',regex=True),
    errors="coerce")
# Fix the cm convert to inches
df4.loc[df4.Display == 15.6,"Display"] = 39.624 # 39.624 / 2.54
df4.Display = df4.Display / 2.54
# Fill NAs with mean
disp_med = df4.Display.mean()
df4.Display = df4.Display.fillna(value=disp_med)
#======================================================
# Convert price to a number
df4.Price = df4.Price.str.replace(r'[^0-9]','',regex=True).astype('float')
# Convert from INR to USD
df4["Price-USD"] = df4["Price"]*0.013

In [165]:
#df4.tail()
df4.head(2)

,Unnamed: 0,Name,Processor,RAM,Operating System,Storage,Display,Warranty,Price,rating,Company,Product,Price-USD
0,0,Lenovo Ideapad S145 Core i5 10th Gen - (8 GB/1...,Intel Core i5 Processor (10th Gen),8.0,64-bit win10,1 TB HDD,15.598425,1 Year Onsite Warranty,43990.0,3.9,Lenovo,Ideapad S145,571.87
1,1,Lenovo IdeaPad Core i3 11th Gen - (8 GB/256 GB...,Intel Core i3 Processor (11th Gen),8.0,64-bit win10,256 GB SSD,14.000000,1 Year Onsite Warranty,43990.0,4.2,Lenovo,IdeaPad Core,571.87

In [166]:
df4['RAM'].unique()

array([ 8.,  4., 16., 32., nan, 12.])

In [167]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        550 non-null    int64
 1   Name              550 non-null    object
 2   Processor         550 non-null    object
 3   RAM               549 non-null    float64
 4   Operating System  550 non-null    object
 5   Storage           550 non-null    object
 6   Display           550 non-null    float64
 7   Warranty          550 non-null    object
 8   Price             550 non-null    float64
 9   rating            550 non-null    float64
 10  Company           550 non-null    object
 11  Product           550 non-null    object
 12  Price-USD         550 non-null    float64
dtypes: float64(5), int64(1), object(7)
memory usage: 56.0+ KB

### Combining Datasets:

In [168]:
display(df2.head(1), df4.head(1))

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price-USD
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,mac,1.37kg,1339.69,1513.8497

,Unnamed: 0,Name,Processor,RAM,Operating System,Storage,Display,Warranty,Price,rating,Company,Product,Price-USD
0,0,Lenovo Ideapad S145 Core i5 10th Gen - (8 GB/1...,Intel Core i5 Processor (10th Gen),8.0,64-bit win10,1 TB HDD,15.598425,1 Year Onsite Warranty,43990.0,3.9,Lenovo,Ideapad S145,571.87

In [169]:
df2.rename(columns={'Ram': 'RAM', 'OpSys':'Operating System', 'Cpu':'CPU', 'Inches':'Display'}, inplace=True)
df2.head(1)

,laptop_ID,Company,Product,TypeName,Display,ScreenResolution,CPU,RAM,Memory,Gpu,Operating System,Weight,Price_euros,Price-USD
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,mac,1.37kg,1339.69,1513.8497

In [170]:
df4.rename(columns={'Storage': 'Memory', 'Processor':'CPU'}, inplace=True)
df4.head(1)

,Unnamed: 0,Name,CPU,RAM,Operating System,Memory,Display,Warranty,Price,rating,Company,Product,Price-USD
0,0,Lenovo Ideapad S145 Core i5 10th Gen - (8 GB/1...,Intel Core i5 Processor (10th Gen),8.0,64-bit win10,1 TB HDD,15.598425,1 Year Onsite Warranty,43990.0,3.9,Lenovo,Ideapad S145,571.87

In [171]:
#dataset_merg = df2.concat(df4)
dataset_merg = pd.concat([df2, df4])
dataset_merg

,laptop_ID,Company,Product,TypeName,Display,ScreenResolution,CPU,RAM,Memory,Gpu,Operating System,Weight,Price_euros,Price-USD,Unnamed: 0,Name,Warranty,Price,rating
0,1.0,Apple,MacBook Pro,Ultrabook,13.300000,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8.0,128GB SSD,Intel Iris Plus Graphics 640,mac,1.37kg,1339.69,1513.8497,NaN,NaN,NaN,NaN,NaN
1,2.0,Apple,Macbook Air,Ultrabook,13.300000,1440x900,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,mac,1.34kg,898.94,1015.8022,NaN,NaN,NaN,NaN,NaN
2,3.0,HP,250 G6,Notebook,15.600000,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,649.7500,NaN,NaN,NaN,NaN,NaN
3,4.0,Apple,MacBook Pro,Ultrabook,15.400000,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16.0,512GB SSD,AMD Radeon Pro 455,mac,1.83kg,2537.45,2867.3185,NaN,NaN,NaN,NaN,NaN
4,5.0,Apple,MacBook Pro,Ultrabook,13.300000,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8.0,256GB SSD,Intel Iris Plus Graphics 650,mac,1.37kg,1803.60,2038.0680,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,NaN,ASUS,ASUS TUF,NaN,14.708664,NaN,AMD Ryzen 7 Octa Core Processor,8.0,256 GB SSD,NaN,64-bit win10,NaN,NaN,1780.8700,545.0,ASUS ASUS TUF Dash Series Core i7 11th Gen - (...,1 Year Onsite Warranty,136990.0,4.9
546,NaN,ASUS,Ryzen 3,NaN,14.000000,NaN,Intel Core i7 Processor (10th Gen),16.0,1 TB HDD|256 GB SSD,NaN,64-bit win10,NaN,NaN,492.7000,546.0,ASUS Ryzen 3 Dual Core 3250U - (4 GB/256 GB SS...,1 Year Onsite Warranty,37900.0,3.9
547,NaN,MSI,GL65 Leopard,NaN,13.299213,NaN,AMD Ryzen 7 Quad Core Processor,4.0,1 TB HDD|512 GB SSD,NaN,64-bit win10,NaN,NaN,1429.8700,547.0,MSI GL65 Leopard Core i7 10th Gen - (16 GB/1 T...,1 Year Onsite Warranty,109990.0,3.5
548,NaN,HP,Pavilion Core,NaN,15.598425,NaN,AMD Ryzen 7 Octa Core Processor,16.0,512 GB SSD,NaN,win10,NaN,NaN,1586.0000,548.0,HP Pavilion Core i7 9th Gen - (12 GB/1 TB HDD/...,1 Year Manufacturer Warranty on the Device and...,122000.0,4.5
549,NaN,DELL,GAMING G5,NaN,14.000000,NaN,Intel Core i5 Processor (10th Gen),12.0,1 TB HDD|256 GB SSD,NaN,64-bit win10,NaN,NaN,1039.8700,549.0,DELL GAMING G5 SERIES Core i5 10th Gen - (8 GB...,1 Year Onsite Warranty,79990.0,4.1

In [172]:
dataset_merg.to_csv("Final_Laptop.csv", encoding="utf-8")

In [173]:
df_Final= pd.read_csv('final_laptop.csv', encoding='latin-1')
df_Final.head(2)

,Unnamed: 0,laptop_ID,Company,Product,TypeName,Display,ScreenResolution,CPU,RAM,Memory,Gpu,Operating System,Weight,Price_euros,Price-USD,Unnamed: 0.1,Name,Warranty,Price,rating
0,0,1.0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8.0,128GB SSD,Intel Iris Plus Graphics 640,mac,1.37kg,1339.69,1513.8497,NaN,NaN,NaN,NaN,NaN
1,1,2.0,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,mac,1.34kg,898.94,1015.8022,NaN,NaN,NaN,NaN,NaN

In [174]:
df_Final.shape

(1853, 20)

#### 1- https://www.kaggle.com/muhammetvarl/laptop-price  == df2
#### 2- https://www.kaggle.com/asifraza14/laptop-price-prediction-using-specifications == df4

In [175]:
def ram_dict(x):
    if x == "Upgradable":
        return "512"
    else:
        return 
df4["RAM"]= df4.RAM.apply(ram_dict)